# Generated by Django 6.0.2 on 2026-03-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('route_type', models.CharField(choices=[('express', 'Express'), ('regular', 'Regular'), ('feeder', 'Feeder')], default='regular', max_length=20)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('total_duration_minutes', models.IntegerField()),
                ('fare_cop', models.DecimalField(decimal_places=0, max_digits=10)),
                ('frequency_minutes', models.IntegerField(default=15, help_text='How often the bus comes (minutes)')),
            ],
            options={
                'ordering': ['route_number'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_transfer_point', models.BooleanField(default=False)),
                ('arrival_offset_minutes', models.IntegerField(help_text='Minutes from departure of first stop')),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark for reference', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StepInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_type', models.CharField(choices=[('walk', 'Walk'), ('wait', 'Wait'), ('board', 'Board Bus'), ('ride', 'Ride'), ('transfer', 'Transfer'), ('exit', 'Exit Bus'), ('arrive', 'Arrive')], max_length=20)),
                ('title_en', models.CharField(max_length=200)),
                ('title_es', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_es', models.TextField()),
                ('tip_en', models.CharField(blank=True, max_length=300)),
                ('tip_es', models.CharField(blank=True, max_length=300)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routes.route')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.stop')),
            ],
            options={
                'ordering': ['route', 'step_number'],
            },
        ),
    ]
