# Generated by Django 4.2.29 on 2026-03-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Ruta Comercial Hotelera', max_length=100)),
                ('origen', models.CharField(default='Universidad EAFIT', max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tiempo_estimado_minutos', models.IntegerField(help_text='Duración aproximada en minutos')),
            ],
        ),
    ]
