# Generated by Django 4.2.29 on 2026-03-08 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('barrio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
        migrations.CreateModel(
            name='RutaBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ruta', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('tipo_servicio', models.CharField(default='estandar', max_length=20)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_estimado_minutos', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViajeCompleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_latitud', models.FloatField()),
                ('origen_longitud', models.FloatField()),
                ('destino_latitud', models.FloatField()),
                ('destino_longitud', models.FloatField()),
                ('duracion_total_minutos', models.IntegerField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_transbordos', models.IntegerField(default=0)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='valido', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('parada_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramos_destino', to='rutas.parada')),
                ('parada_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramos_origen', to='rutas.parada')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.rutabus')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='rutas.viajecompleto')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoTransbordo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_espera_minutos', models.IntegerField()),
                ('distancia_caminata_metros', models.IntegerField(default=0)),
                ('instrucciones_detalladas', models.TextField(blank=True, null=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.parada')),
                ('ruta_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_dest', to='rutas.rutabus')),
                ('ruta_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_origen', to='rutas.rutabus')),
                ('tramo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transbordo', to='rutas.tramo')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioParada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_paso', models.TimeField()),
                ('orden', models.IntegerField()),
                ('dias_operacion', models.CharField(default='LUN-VIE', max_length=20)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas.rutabus')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ventaja', models.CharField(max_length=200)),
                ('orden_prioridad', models.IntegerField(default=1)),
                ('viaje_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='rutas.viajecompleto')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertenciaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_advertencia', models.CharField(max_length=30)),
                ('mensaje', models.TextField()),
                ('severidad', models.CharField(default='media', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to='rutas.viajecompleto')),
            ],
        ),
    ]
