# Generated by Django 4.2.29 on 2026-03-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='paradas',
            field=models.TextField(default='Sin especificar', help_text='Ej: Estación Poblado, Av. Las Vegas, EAFIT'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='transbordos',
            field=models.IntegerField(default=0, help_text='Cantidad de transbordos (0 = Ruta directa)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(default='Universidad EAFIT', max_length=100),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(help_text='Ej: Integrado Metro 132i', max_length=100),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(help_text='Punto de partida del usuario', max_length=100),
        ),
    ]
