# Generated by Django 4.2.29 on 2026-03-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajecompleto',
            old_name='usuario',
            new_name='usuario_viaje',
        ),
    ]
