# Generated by Django 4.2.29 on 2026-03-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_ruta_paradas_ruta_transbordos_alter_ruta_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='precio',
            field=models.IntegerField(default=3200, help_text='Precio en COP'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='paradas',
            field=models.TextField(default='Sin especificar', help_text='Separadas por coma. Ej: Estación Poblado, Av. Las Vegas, EAFIT'),
        ),
    ]
