# Generated by Django 4.2.29 on 2026-03-15 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_ruta_precio_alter_ruta_paradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_campus_eafit', models.BooleanField(default=False, help_text='Marca esta casilla solo para la Universidad EAFIT')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='tiempo_estimado_minutos',
            new_name='tiempo_estimado_min',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='paradas',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='transbordos',
        ),
        migrations.AddField(
            model_name='ruta',
            name='es_directa',
            field=models.BooleanField(default=True, help_text='¿Requiere transbordo?'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(help_text='Ej: Circular Sur 302', max_length=100),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='precio',
            field=models.IntegerField(help_text='Precio en COP'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_como_destino', to='rutas.lugar'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_como_origen', to='rutas.lugar'),
        ),
    ]
