# Generated by Django 4.2.29 on 2026-03-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_lugar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={},
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='es_campus_eafit',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='es_directa',
        ),
        migrations.AddField(
            model_name='ruta',
            name='paradas_intermedias',
            field=models.TextField(blank=True, help_text='Nombres separados por comas. Ej: Av Las Vegas, Estación Poblado, Milla de Oro'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.FloatField(default=6.2006, help_text='Ejemplo: 6.2006 (Usar punto para decimales)'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.FloatField(default=-75.5784, help_text='Ejemplo: -75.5784'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='rutas.lugar'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(help_text='Ej: Poblado 134, Metro, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='rutas.lugar'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tiempo_estimado_min',
            field=models.IntegerField(help_text='Tiempo en minutos'),
        ),
    ]
